version: '3.2'

services:
  caddy:
    image: abiosoft/caddy:no-stats
    restart: "no"
    environment:
      ACME_AGREE: 'true'
    volumes:
      - caddy_data:/root/.caddy
      - ./Caddyfile:/etc/Caddyfile:ro
    ports:
      - published: "${RPNOW_PORT-80}"
        target: 80
      - published: "${RPNOW_SSL_PORT-443}"
        target: 443
    networks:
      - front-layer

  rpnow:
    image: rpnow/rpnow
    build: .
    restart: on-failure
    depends_on:
      - db
      - redis
    environment:
      RPNOW_DB_HOST: 'db'
      RPNOW_REDIS_HOST: 'redis'
      RPNOW_TRUST_PROXY: 'true'
    networks:
      - front-layer
      - back-layer

  db:
    image: mongo:3.6
    restart: on-failure
    volumes:
      - db_data:/data/db
    networks:
      - back-layer

  redis:
    image: redis:4-32bit # 32bit is for decreased memory usage, see docs
    restart: on-failure
    networks:
      - back-layer

networks:
  front-layer:
  back-layer:

volumes:
  caddy_data:
  db_data:
