version: '2'

services:
  web:
    depends_on:
      - api
      - web_build
    image: "nginx:1.10"
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - api

  web_build:
    image: "node:8"
    working_dir: /root/client
    volumes:
      - ./client/app:/root/client/app:ro
      - ./client/bower.json:/root/client/bower.json:ro
      - ./client/gulpfile.js:/root/client/gulpfile.js:ro
      - ./client/package.json:/root/client/package.json:ro
      - ./client/package-lock.json:/root/client/package-lock.json:ro
      - build_npm:/root/client/node_modules/
      - build_bower:/root/client/bower_components/

  api:
    depends_on:
      - db
    image: "node:8"
    working_dir: /root/api
    volumes:
      - ./server/src:/root/api/src
      - ./server/jasmine.json:/root/api/jasmine.json
      - ./server/package.json:/root/api/package.json
      - ./server/package-lock.json:/root/api/package-lock.json:ro
      - api_npm:/root/api/node_modules/
    environment:
      DB_HOST: db
    links:
      - db
    command: npm start

  db:
    image: "mongo:3.4"
    volumes:
      - db_data:/data/db
    restart: always

volumes:
  db_data:
  build_bower:
  build_npm:
  api_npm:
