version: '2.0'

services:
  rpnow:
    container_name: rpnow
    image: rpnow/rpnow:php
    build: .
    volumes:
      - ./php-server/src:/var/www/html/src:ro
      - ./php-server/vendor:/var/www/html/vendor:ro
      - ./php-server/.htaccess:/var/www/html/.htaccess:ro
      - ./php-server/index.php:/var/www/html/index.php:ro
      - ./php-server/db-settings.php:/var/www/html/db-settings.php:ro
      - ./client/dist/rpnow:/var/www/html/client-files:ro
    ports:
      - "13000:80"
  db:
    container_name: rpnow_db
    image: mysql:5.5
    environment:
      MYSQL_DATABASE: rpnow
      MYSQL_USER: nigel
      MYSQL_PASSWORD: abc123
      MYSQL_ROOT_PASSWORD: abc123
