version: '3.2'

services:
  web:
    image: "nginx:1.15"
    restart: on-failure
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./client/dist.${RPNOW_DEV_PROD}:/usr/share/nginx/html:ro
    ports:
      - "${RPNOW_PORT}:80"
    networks:
      - front-layer

  web_build:
    image: "node:8"
    restart: on-failure
    working_dir: /root/client
    volumes:
      - ./client/dist.${RPNOW_DEV_PROD}:/root/client/dist.${RPNOW_DEV_PROD}:rw
      - ./client/app:/root/client/app:ro
      - ./client/bower.json:/root/client/bower.json:ro
      - ./client/gulpfile.js:/root/client/gulpfile.js:ro
      - ./client/package.json:/root/client/package.json:ro
      - ./client/package-lock.json:/root/client/package-lock.json:ro
      - build_npm:/root/client/node_modules/
      - build_bower:/root/client/bower_components/
    command: npm run gulp -- ${RPNOW_BUILD_RUN_SCRIPT}

  api:
    image: "node:8"
    restart: on-failure
    depends_on:
      - db
    working_dir: /root/api
    volumes:
      - ./server/src:/root/api/src
      - ./server/jasmine.json:/root/api/jasmine.json
      - ./server/package.json:/root/api/package.json
      - ./server/package-lock.json:/root/api/package-lock.json:ro
      - api_npm:/root/api/node_modules/
    environment:
      DB_HOST: db
    networks:
      - front-layer
      - back-layer
    command: npm run ${RPNOW_API_RUN_SCRIPT}

  db:
    image: "mongo:3.6"
    restart: on-failure
    volumes:
      - db_data:/data/db
    networks:
      - back-layer

networks:
  front-layer:
  back-layer:

volumes:
  db_data:
  build_bower:
  build_npm:
  api_npm:
