version: '2'

services:
  web:
    depends_on:
      - api
      - web_build
    image: "nginx:1.10"
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./client/build:/usr/share/nginx/html:ro
    links:
      - api

  web_build:
    image: "node:6"
    working_dir: /root/rpnow2
    volumes:
      - ./client:/root/rpnow2
    command: npm start

  api:
    depends_on:
      - db
    image: "node:6"
    working_dir: /root/rpnow2
    volumes:
      - ./server:/root/rpnow2
    environment:
      DB_HOST: db
    links:
      - db
    command: npm start

  db:
    image: "mongo:3.4"
    volumes:
      - db_data:/data/db
    restart: always

volumes:
  db_data:
