version: '2'

services:
  web:
    ports:
      - "8080:80"
  
  web_build:
    environment:
      RPNOW_PRODUCTION: dev
    restart: always

  api:
    command: npm run start-dev
    ports:
      - "3000:3000"

  web_debug:
    depends_on:
      - web_build
    image: "httpd:2.2"
    volumes:
      - ./client/build:/usr/local/apache2/htdocs:ro
    ports:
      - "8181:80"

  db_debug:
    depends_on:
      - db
    image: "mongo-express:0.38"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
    links: 
      - db
    ports:
      - "8282:8081"
