version: '2'

services:
  web:
    ports:
      - "8080:80"

  node:
    volumes:
      - node_modules_dev:/root/rpnow2/node_modules
    command: npm run docker-compose-runner-dev
    ports:
      - "3000:3000"
  
  build:
    environment:
      RPNOW_PRODUCTION: dev

  web_debug:
    depends_on:
      - build
    image: "httpd:2.2"
    volumes:
      - build_www:/usr/local/apache2/htdocs:ro
    ports:
      - "8181:80"

  db_debug:
    depends_on:
      - db
    image: "mongo-express:0.38"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
    links: 
      - db
    ports:
      - "8282:8081"

volumes:
  node_modules_dev: