version: '2'

services:
  web:
    ports:
      - "80:80"
    restart: always
  
  api:
    restart: always
  
  web_build:
    environment:
      RPNOW_PRODUCTION: production
    restart: "on-failure"
