version: '2'

services:

  node:
    depends_on:
      - db
    image: "node:6"
    ports:
      - "8080:8080"
    user: node
    environment:
      PORT: '8080'
      DB_HOST: db
    volumes:
      - ./package.json:/home/node/rpnow2/package.json:ro
      - ./src:/home/node/rpnow2/src:ro
      - ./build:/home/node/rpnow2/build:ro
      - node_modules:/home/node/rpnow2/node_modules
    working_dir: /home/node/rpnow2
    command: npm run docker-compose-runner
  
  db:
    image: "mongo:3.4"
    volumes:
      - db_data:/data/db

volumes:
  node_modules:
  db_data:
