version: '2'

services:

  web:
    depends_on:
      - node
    image: "nginx:1.10"
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/www:/usr/share/nginx/html:ro
    links:
      - node

  node:
    depends_on:
      - db
    image: "node:6"
    user: node
    environment:
      PORT: '3000'
      DB_HOST: db
    working_dir: /home/node/rpnow2
    volumes:
      - ./package.json:/home/node/rpnow2/package.json:ro
      - ./src:/home/node/rpnow2/src:ro
      - ./build:/home/node/rpnow2/build:ro
      - node_modules:/home/node/rpnow2/node_modules
    command: npm run docker-compose-runner
  
  db:
    image: "mongo:3.4"
    volumes:
      - db_data:/data/db

volumes:
  node_modules:
  db_data:
