version: '3.2'

services:
  caddy:
    image: abiosoft/caddy
    restart: "no"
    volumes:
      - caddy_certs:/etc/caddycerts
      - ./Caddyfile:/etc/Caddyfile:ro
    ports:
      - "${RPNOW_PORT-80}:80"
      - "${RPNOW_SSL_PORT-443}:443"
    networks:
      - front-layer
    # http2 is off because... no websockets in http2!
    command: ["-agree", "-conf", "/etc/Caddyfile", "-http2=false", "-ca", "${ACME_CA-https://acme-v02.api.letsencrypt.org/directory}"]
    deploy:
      placement:
        constraints: [node.role == manager]

  rpnow:
    image: rpnow/rpnow
    build: .
    restart: on-failure
    depends_on:
      - db
    environment:
      DB_HOST: db
    networks:
      - front-layer
      - back-layer

  db:
    image: mongo:3.6
    restart: on-failure
    volumes:
      - db_data:/data/db
    networks:
      - back-layer

networks:
  front-layer:
  back-layer:

volumes:
  caddy_certs:
  db_data:
