version: '3.2'

services:
  caddy:
    ports:
      - "2015:2015"

  rpnow:
    volumes:
      - ./client/dist:/root/client/dist:ro
      - ./server/src:/root/server/src:ro
      - ./server/admin:/root/server/admin:ro
      - ./server/jasmine.json:/root/server/jasmine.json:ro
      - ./server/package.json:/root/server/package.json:ro
      - ./server/package-lock.json:/root/server/package-lock.json:ro
    environment:
      RPNOW_CORS: 'true'
      RPNOW_LOG_LEVEL: 'debug'
      RPNOW_BUNDLE_COMPRESSION: ''
    command: npm run start-dev

  db:
    networks:
      - admin-layer

  db_debug:
    image: "mongo-express:latest"
    depends_on:
      - db
    environment:
      ME_CONFIG_MONGODB_SERVER: db
    ports:
      - "8282:8081"
    networks:
      - admin-layer

networks:
  admin-layer:
