version: '2.0'

services:
  rpnow:
    container_name: rpnow
    image: rpnow/rpnow:php
    build: .
    volumes:
      - ./php-server:/var/www/html:ro
      - ./client/dist:/var/www/bundle:ro
    ports:
      - "13000:80"
