version: '2'

services:
  node:
    depends_on:
      - db
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./server:/srv/server
      - node_modules:/srv/node_modules
    environment:
      DB_HOST: db
  
  db:
    image: "mongo:3.4"
    volumes:
      - db_data:/data/db

volumes:
  node_modules:
  db_data:
