version: '2'

services:

  web:
    depends_on:
      - node
      - build
    image: "nginx:1.10"
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - build_www:/usr/share/nginx/html:ro
    links:
      - node

  node:
    depends_on:
      - db
    image: "node:6"
    environment:
      PORT: '3000'
      DB_HOST: db
    working_dir: /root/rpnow2
    volumes:
      - ./package.json:/root/rpnow2/package.json:ro
      - ./src:/root/rpnow2/src:ro
      - node_modules_prod:/root/rpnow2/node_modules
    command: npm run docker-compose-runner

  build:
    image: "node:6"
    working_dir: /root/rpnow2
    volumes:
      - ./package.json:/root/rpnow2/package.json:ro
      - ./gulpfile.js:/root/rpnow2/gulpfile.js:ro
      - ./src:/root/rpnow2/src:ro
      - build_www:/root/rpnow2/build
      - node_modules_dev:/root/rpnow2/node_modules
    command: npm run docker-compose-build

  db:
    image: "mongo:3.4"
    volumes:
      - db_data:/data/db

volumes:
  build_www:
  db_data:
  node_modules_dev:
  node_modules_prod:
