version: '2'

services:
  web:
    ports:
      - "8080:80"
    volumes:
      - ./client/dist.dev:/usr/share/nginx/html:ro
  
  web_build:
    environment:
      RPNOW_PRODUCTION: dev
    volumes:
      - ./client/dist.dev:/root/client/dist.dev:rw
    command: npm run gulp -- watch-dev

  api:
    volumes:
      - ./server/spec:/root/api/spec
    command: npm run start-dev
    ports:
      - "3000:3000"

  db_debug:
    depends_on:
      - db
    image: "mongo-express:0.38"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
    links: 
      - db
    ports:
      - "8282:8081"
