apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    name: redis
  ports:
    - name: redis
      port: 6379

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
        - image: redis:4
          name: redis
          ports:
            - name: redis
              containerPort: 6379
          resources:
            requests:
              cpu: "0"
              memory: 20Mi
            limits:
              cpu: "0.25"
              memory: 100Mi
